### ISSUE TITLE
Pyrometheus tests no longer work after fresh install

### ISSUE THREAD

**Issue by MTCam** [pyrometheus/pyrometheus#27]
After a fresh install of pyrometheus, I get the following errors when running pytest on commodity linux and macos machines:

```
FAILED test_codegen.py::test_get_rate_coefficients[numpy-uiuc] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_rate_coefficients[numpy-sanDiego] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_pressure[numpy-uiuc] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_pressure[numpy-sanDiego] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_thermo_properties[numpy-uiuc] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_thermo_properties[numpy-sanDiego] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_temperature[numpy-uiuc] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_get_temperature[numpy-sanDiego] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_kinetics[numpy-uiuc-C2H4-3.0-1e-07] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_kinetics[numpy-sanDiego-H2-0.5-1e-06] - NameError: name 'jnp' is not defined
FAILED test_codegen.py::test_falloff_kinetics[UConn32-C2H4-3] - assert 1.1525208115781461e-14 < 1e-14
```

**Comment by inducer** [comment]
Thanks for reporting this!

The `jnp` thing is my bad, I should have caught that during review. These snippets:
https://github.com/ecisneros8/pyrometheus/blob/46767dc853997344a8a896fbac43bce9e3dbd215/test/test_codegen.py#L117-L120
end up referencing Jax numpy even when it's not installed. @cmikida2 Could you cook up a fix?

I'm not super worried  about the missed tolerance; I'd suggest we just bump it up. @MTCam, could you submit a PR that does this?

**Comment by MTCam** [comment]
#28

**Comment by cmikida2** [comment]
#29 (really sorry about this, it was *my* bad for writing that code)

**Comment by inducer** [comment]
Thanks! See also #30.

**Comment by MTCam** [comment]
No worries at all, everyone!  This did not cause any failures aside from the testing ones.  I just wanted to bring the failing tests to your attention.
