### ISSUE TITLE
Missing Intersphinx symbols on readthedocs

### ISSUE THREAD

**Issue by matthiasdiener** [pyrometheus/pyrometheus#63]
Currently, the Intersphinx inventory for the `latest` doc build branch (which is using the `arraycontext` branch of pyrometheus) does not seem to contain any symbols related to pyrometheus anymore:

```
$ python -m sphinx.ext.intersphinx https://pyrometheus.readthedocs.io/en/latest/objects.inv | grep pyrometheus
	index                                    Welcome to pyrometheus’s documentation! : index.html
```

The `transport-new` branch of the doc build has those symbols:

```
$ python -m sphinx.ext.intersphinx https://pyrometheus.readthedocs.io/en/transport-new/objects.inv | grep pyrometheus
	pyrometheus.codegen.python.gen_thermochem_code codegen.html#pyrometheus.codegen.python.gen_thermochem_code
	pyrometheus.codegen.python.get_thermochem_class codegen.html#pyrometheus.codegen.python.get_thermochem_class
	pyrometheus                              codegen.html#module-pyrometheus
	pyrometheus.chem_expr                    codegen.html#module-pyrometheus.chem_expr
	pyrometheus.codegen.python               codegen.html#module-pyrometheus.codegen.python
	index                                    Welcome to pyrometheus’s documentation! : index.html
```

(see also the doc builds: https://readthedocs.org/projects/pyrometheus/builds/)

This currently leads to CI errors in mirgecom, e.g. https://github.com/illinois-ceesd/mirgecom/actions/runs/3934929902/jobs/6730137560 

Maybe the `latest` doc build should use the `main` branch of pyrometheus?

**Comment by ecisneros8** [comment]
My bad, I was messing with the docs and surely broke them. @matthiasdiener did you succeed in setting `latest` doc to `main`? Let me know otherwise.

**Comment by matthiasdiener** [comment]
> @matthiasdiener did you succeed in setting `latest` doc to `main`? Let me know otherwise.

I don't have permissions to change the branch on readthedocs, but on a local doc build on my machine, it seems that the inventory is correct with the `main` branch (while I can reproduce the missing. symbols with the `arraycontext` branch).

**Comment by inducer** [comment]
Rtd was pointing at `arraycontext` as the default branch as opposed to `main`. I just changed this back.

**Comment by MTCam** [comment]
The MC CI doc build error is still occurring after the latest round of fixes:
https://github.com/illinois-ceesd/mirgecom/actions/runs/3944500055/jobs/6760813990#step:4:1651

Do we need to do something in MC to fix?
