### ISSUE TITLE
Missing symbols in intersphinx from generated code

### ISSUE THREAD

**Issue by inducer** [pyrometheus/pyrometheus#65]

**Comment by matthiasdiener** [comment]
maybe this is helpful: https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process

**Comment by inducer** [comment]
First attempt: d528a0fdbcc6d9ba1a5fcda36723ca17be4205a0

**Comment by inducer** [comment]
7b36ee850a908a6508ce36b3008770b53fae98e0 ultimately fixed this I think. I dislike RTD even more now than I did before.
