### ISSUE TITLE
Simplify MIRGE-Com testing?

### ISSUE THREAD

**Issue by tulioricci** [pyrometheus/pyrometheus#80]
The half-full glass: only two tests are currently using pyrometheus in MIRGE-Com. Can we just test these 2 files?

(in mirgecom/test) grep -il "pyro" *py
> test_eos.py
> test_transport.py

The half-empty glass: how can we only be testing mixtures in these two files? We have a bunch of other things that depend on mixtures. This is scary.

**Comment by ecisneros8** [comment]
I don't think this discussion belongs to Pyro. It seems to me that you decide what tests to run in mirgecom.

**Comment by tulioricci** [comment]
Closed since we don't test mirge-com anymore.
